# import pyspark
# import datetime
# import time
# import requests
# import traceback
# import bs4
# import random
# from pyspark.sql.functions import *
# from pyspark.sql.types import *
# import re

# spark = pyspark.sql.SparkSession.builder.getOrCreate()

# dt = datetime.datetime.now()
# df = spark.read.json(f'/lake/red/korea_racing_authority/race_detail_result').drop("year")
# df = df.na.replace('-', None)
# df = df.drop("age")
# df = df.drop("ageCond")
# df = df.withColumn(
#     "birthday", 
#     to_date(col("birthday").cast("string"), "yyyyMMdd")
# )
# df = df.withColumn("buga1", col("buga1").cast(LongType()))
# df = df.withColumn("buga2", col("buga2").cast(LongType()))
# df = df.withColumn("buga3", col("buga3").cast(LongType()))
# df = df.withColumn("chaksun1", col("chaksun1").cast(LongType()))
# df = df.withColumn("chaksun2", col("chaksun2").cast(LongType()))
# df = df.withColumn("chaksun3", col("chaksun3").cast(LongType()))
# df = df.withColumn("chaksun4", col("chaksun4").cast(LongType()))
# df = df.withColumn("chaksun5", col("chaksun5").cast(LongType()))
# df = df.withColumn("ilsu", col("ilsu").cast(ShortType()))
# df = df.withColumn("ord", col("ord").cast(ShortType()))
# df = df.withColumn("ordG1f", col("ordG1f").cast(ShortType()))
# df = df.withColumn("ordS1f", col("ordS1f").cast(ShortType()))
# df = df.withColumn("plcOdds", col("plcOdds").cast(DoubleType()))
# df = df.withColumn("rankRise", col("rankRise").cast(ShortType()))
# df = df.withColumn("rating", col("rating").cast(ShortType()))
# df = df.withColumn(
#     "rcDate", 
#     to_date(col("rcDate").cast("string"), "yyyyMMdd")
# )
# df = df.withColumn("rcDist", col("rcDist").cast(IntegerType()))
# df = df.withColumn("rcTime", col("rcTime").cast(DoubleType()))
# df = df.withColumn("rcTimeG1f", col("rcTimeG1f").cast(DoubleType()))
# df = df.withColumn("rcTimeG2f", col("rcTimeG2f").cast(DoubleType()))
# df = df.withColumn("rcTimeG3f", col("rcTimeG3f").cast(DoubleType()))
# df = df.withColumn("rcTimeS1f", col("rcTimeS1f").cast(DoubleType()))
# df = df.withColumn("rcTime_1c", col("rcTime_1c").cast(DoubleType()))
# df = df.withColumn("rcTime_2c", col("rcTime_2c").cast(DoubleType()))
# df = df.withColumn("rcTime_3c", col("rcTime_3c").cast(DoubleType()))
# df = df.withColumn("rcTime_400", col("rcTime_400").cast(DoubleType()))
# df = df.withColumn("rcTime_4c", col("rcTime_4c").cast(DoubleType()))
# df = df.withColumn("wgBudam", col("wgBudam").cast(DoubleType()))
# df = df.withColumn("winOdds", col("winOdds").cast(DoubleType()))


# df2 = df.coalesce(5) 

# df2.printSchema()
# df2.show()

# df2.write.mode('overwrite').option('compression', 'snappy').parquet(f'/lake/yellow/korea_racing_authority/race_detail_result')

# # << race_detail_result >>
# # root
# #  |-- age: string (nullable = true)
# #  |-- ageCond: string (nullable = true)
# #  |-- birthday: string (nullable = true)
# #  |-- budam: string (nullable = true)
# #  |-- buga1: string (nullable = true)
# #  |-- buga2: string (nullable = true)
# #  |-- buga3: string (nullable = true)
# #  |-- chaksun1: string (nullable = true)
# #  |-- chaksun2: string (nullable = true)
# #  |-- chaksun3: string (nullable = true)
# #  |-- chaksun4: string (nullable = true)
# #  |-- chaksun5: string (nullable = true)
# #  |-- chulNo: string (nullable = true)
# #  |-- diffUnit: string (nullable = true)
# #  |-- g2f: string (nullable = true)
# #  |-- g3f_4c: string (nullable = true)
# #  |-- g4f_3c: string (nullable = true)
# #  |-- g6f_2c: string (nullable = true)
# #  |-- g8f_1c: string (nullable = true)
# #  |-- hrName: string (nullable = true)
# #  |-- hrNo: string (nullable = true)
# #  |-- hrTool: string (nullable = true)
# #  |-- ilsu: string (nullable = true)
# #  |-- jkName: string (nullable = true)
# #  |-- jkNo: string (nullable = true)
# #  |-- meet: string (nullable = true)
# #  |-- name: string (nullable = true)
# #  |-- ord: string (nullable = true)
# #  |-- ordBigo: string (nullable = true)
# #  |-- ordG1f: string (nullable = true)
# #  |-- ordS1f: string (nullable = true)
# #  |-- owName: string (nullable = true)
# #  |-- owNo: string (nullable = true)
# #  |-- plcOdds: string (nullable = true)
# #  |-- prizeCond: string (nullable = true)
# #  |-- rank: string (nullable = true)
# #  |-- rankRise: string (nullable = true)
# #  |-- rating: string (nullable = true)
# #  |-- rcDate: string (nullable = true)
# #  |-- rcDay: string (nullable = true)
# #  |-- rcDist: string (nullable = true)
# #  |-- rcName: string (nullable = true)
# #  |-- rcNo: string (nullable = true)
# #  |-- rcTime: string (nullable = true)
# #  |-- rcTimeG1f: string (nullable = true)
# #  |-- rcTimeG2f: string (nullable = true)
# #  |-- rcTimeG3f: string (nullable = true)
# #  |-- rcTimeS1f: string (nullable = true)
# #  |-- rcTime_1c: string (nullable = true)
# #  |-- rcTime_2c: string (nullable = true)
# #  |-- rcTime_3c: string (nullable = true)
# #  |-- rcTime_400: string (nullable = true)
# #  |-- rcTime_4c: string (nullable = true)
# #  |-- sex: string (nullable = true)
# #  |-- trName: string (nullable = true)
# #  |-- trNo: string (nullable = true)
# #  |-- track: string (nullable = true)
# #  |-- weather: string (nullable = true)
# #  |-- wgBudam: string (nullable = true)
# #  |-- wgBudamBigo: string (nullable = true)
# #  |-- wgHr: string (nullable = true)
# #  |-- wgJk: string (nullable = true)
# #  |-- winOdds: string (nullable = true)
# #  |-- year: integer (nullable = true)

